import { StyleSheet, Animated } from "react-native";
import {
  hp,
  wp,
  color,
  isANDROID,
} from "../../Components/CommonUtills/ThemeHelper";

const Styles = StyleSheet.create({
  ImgBg: {
    paddingBottom: hp(8),
    paddingHorizontal: wp(4.2),
    flex: 0,
  },
  BackIcon: {
    backgroundColor: color.blueIconBg,
    borderRadius: 100,
    alignSelf: "flex-start",
    position: "absolute",
    top: isANDROID ? hp(2) : hp(6),
    left: wp(4.2),
  },
  Progress: {
    backgroundColor: color.white,
    borderRadius: 100,
    marginBottom: wp(1.5),
    marginTop: isANDROID ? hp(11) : hp(13),
    marginHorizontal: wp(4),
  },
  ProgressGreen: {
    backgroundColor: color.greenMint,
    width: wp(20),
    height: hp(1.8),
    borderRadius: 100,
  },
  Sec: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: wp(2),
    marginHorizontal: wp(4),
  },
  SecTxt: { fontSize: 13, color: color.white },
  QuesTxt: { fontSize: 15, color: color.white, alignSelf: "center" },
  Line: {
    marginTop: hp(3),
    height: 0.3,
    backgroundColor: color.blueIconBg,
    marginHorizontal: -wp(4),
  },
  // OverLapView: { marginTop: -hp(10), paddingTop: hp(3) },
  QHead: {
    color: color.gray,
    marginBottom: wp(2),
    fontSize: 15,
    marginLeft: wp(4.2),
  },
  Question: {
    fontSize: 16,
    color: color.blackTheme,
    marginLeft: wp(4.2),
    marginRight: wp(1),
    marginBottom: wp(5),
  },
  Card: {
    backgroundColor: color.white,
    margin: wp(4.2),
    borderRadius: 10,
    paddingHorizontal: wp(3),
    paddingTop: hp(2),
    flex: 1,
    marginTop: -hp(5),
    paddingTop: hp(3),
  },
  BtnV: {
    paddingBottom: hp(1),
    flexDirection: "row",
    alignSelf: "center",
    flex: 0.8,
  },
  AnsView: {
    alignItems: "center",
    justifyContent: "center",
    height: hp(5),
    alignSelf: "center",
  },
  AnsLabel: { color: color.black, fontSize: 16 },
  Ans: {
    color: color.blackTheme,
    fontSize: 18,
    fontWeight: "bold",
  },
  Loader: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonContainer: {
    borderRadius: 100,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: wp(3),
    borderWidth: 0.5,
    marginTop: hp(3),
    alignSelf: "stretch",
  },
  text1: {
    flex: 1,
    letterSpacing: 0.5,
    alignSelf: "center",
    textAlign: "center",
    fontSize: 18,
    marginVertical: isANDROID ? hp(1) : hp(1.3),
  },
});
export default Styles;
